
# Dependencies
FROM node:21-alpine3.19 as deps

WORKDIR /usr/src/app

COPY package-lock.json ./
COPY package.json ./

RUN npm install

# Builder
FROM node:21-alpine3.19 as builder

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules

COPY . .

RUN npm run build

RUN npm ci -f --only-production && npm cache clean --force

# There could be an additional step to run tests


# Production image build 

FROM node:21-alpine3.19 as prod

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist

ENV NODE_ENV=production

USER node

CMD ["node", "dist/main.js"]







